Bootstrap: docker
From: ubuntu:16.04

%post
mkdir /home/something
find /home/something -type d -exec chmod a+rwx {} \;

%runscript
exec /bin/bash -c 'cd /home/something && /bin/bash -l'
# now write into the directory above
# dd if=/dev/zero bs=1M count=1024 of=aa
#
# df -h
